### ISSUE TITLE
er図ほしい

### ISSUE THREAD

**Issue by NotFounds** [enpitut2018/VideoSocialBookmark#150]

**Comment by NotFounds** [comment]
`bundle exec erd --filetype dot`

![image](https://user-images.githubusercontent.com/8983747/49992924-b6c97c00-ffc8-11e8-9ef8-cecff26ca54a.png)

**Comment by kinironote** [comment]
ActiveStorageは https://github.com/enpitut2018/VideoSocialBookmark/commit/c7c0ee7b7718f022fa935f38e62bea463b70b518#diff-8ac4178efcd1769767070c56750aa8b3 で作った、アバター用のものです
ここには書いてないけどuser.avatarでアクセスできるはず
