### ISSUE TITLE
ユーザーページ見れますか？

### ISSUE THREAD

**Issue by NotFounds** [enpitut2018/VideoSocialBookmark#152]
**具体的な内容**
なし

**再現手順**
なし

**スクリーンショット**
なし

**動作環境**
なし

**その他**
なし

**Comment by kinironote** [comment]
?
https://video-social-bookmark.herokuapp.com/users/19
これとか見れます

**Comment by NotFounds** [comment]
https://video-social-bookmark.herokuapp.com/users/17
🤔🤔🤔
