### ISSUE TITLE
Bookmarks

### ISSUE THREAD

**Issue by kinironote** [enpitut2018/VideoSocialBookmark#2]

**Comment by kinironote** [comment]
API
- post
- create
- get
- put
- edit

**Comment by kinironote** [comment]
Model
- url: text
- comment: text
- star_num: int

**Comment by NotFounds** [comment]
star_num -> star_countにしたいです．

あと，starに付いて考えるなら．starモデル/APIを考えないといけないですね．

**Comment by kinironote** [comment]
### Model
- id: int
- user_id: int
- thread_id: int
- comment: text (default '')
- star_count: int (default 0)
- private: bool (default false)
- original_url: string

### API
## POST /api/v1/bookmarks/create
  original_urlからurlを抽出してthreadを特定、登録
  threadsに該当するurlが存在しなければ、新しくthreadを作る
  - Request
    - original_url: string
    - comment: string
    - private: bool (option)
  - Response
    - id: int
## GET /api/v1/bookmarks/:id
  取得
  他人かつprivateは除外
  - Request
  - Response
    - id: int
    - user_id: int
    - thread_id: int
    - comment: text
    - star_count: int
## DELETE /api/v1/bookmarks/:id
  消す
  - Request
  - Response
## GET /api/v1/bookmarks/search
  検索
  - Request/Response
    Users/Bookmarksと同じように(他人かつprivateは除外)

**Comment by kinironote** [comment]
`url`はThreadsと被るので`original_url`だけで良いのでは

**Comment by NotFounds** [comment]
/createエンドポイントは必要なさそうですね
> `POST /api/v1/bookmarks/create`

`POST /api/v1/bookmarks`

**Comment by kinironote** [comment]
GET /api/v1/bookmarks/searchもただのgetなのでGET /api/v1/bookmarksにしました
/api/v1/user/:id/bookmarksいらないのでは？

**Comment by NotFounds** [comment]
> /api/v1/user/:id/bookmarksいらないのでは？
確かに．消しときます．

**Comment by NotFounds** [comment]
#### Query
- `query`
  + **string**
    + 検索文字列
- `user`
  + **string**
    + 対象ユーザーid
    + 指定しない場合はすべてのユーザーから検索
- `page`
  + **int**
    + default: 0
  + ページネーション
- `page_size`
  + **int**
    + default: 20
  + 1ページの件数
- `metadata`
  + **boolean**
    + default: true
  + メタデータを取得するか

#### Responses
- Status: 200
```json
{
    "_metadata": {
        "query": string,
        "user": string,
        "page": int,
        "page_size": int,
        "page_count": int,
        "total_count": int,
        "Links": [
            { "self": string },
            { "first": string },
            { "previous": string },
            { "next": string },
            { "last": string },
        ]
    },
    "bookmarks": [
        {
            "id": int,
            "thread_id": int,
            "thread_url": string,
            "comment": string,
            "private": boolean,
        }
    ]
}
```
