### ISSUE TITLE
プレイリストを作れる/再生できる

### ISSUE THREAD

**Issue by tomoyaf** [enpitut2018/VideoSocialBookmark#29]
いろいろなサイトの動画を組み合わせてプレイリストを作って自動再生させる機能

**Comment by NotFounds** [comment]
yosage

**Comment by NotFounds** [comment]
プレイリストはbookmarkのリスト？
動画のurlのリスト？

**Comment by NotFounds** [comment]
postgresでリストって作れるんだっけ？
作れなかったら再生順管理面倒そう...

## model
### playlist
|name|type|remark|
|:-|:-|:-|
|id|integer||
|user_id|integer||
|title|varchar||
|is_private|boolean||

### playlistitem
|name|type|remark|
|:-|:-|:-|
|id|integer||
|playlist_id|integer||
|bookmark_id|integer||
|index|integer||

**Comment by NotFounds** [comment]
#103 #104
