### ISSUE TITLE
Entry

### ISSUE THREAD

**Issue by kinironote** [enpitut2018/VideoSocialBookmark#3]

**Comment by rikutkb** [comment]
Model
-id :int
-url :text
-title :text
-bookmark_id:int

**Comment by rikutkb** [comment]
API
-get id
-get ranking

**Comment by NotFounds** [comment]
https://github.com/enpitut2018/VideoSocialBookmarkFrontend/issues/2
create時にサムネイル画像を取得or生成し，画像を外部に配置する場合はurlを保持しておきたいです．

**Comment by NotFounds** [comment]
> ```
> - Ranking
> 	-request
> 		-minrank
> 		-maxrank
> 	-response
> 		-Rankinglist
> ```

リクエストパラメータの`minrank`, `maxrank`は?order=に指定する感じですか？

あと，https://github.com/enpitut2018/VideoSocialBookmark/issues/1 のbookmarksのようにpage, per_page, metadataを指定できるようにしたいです．

**Comment by NotFounds** [comment]
threadにurlをhashしたものをindexとして保持させておくことで，他のユーザーが新しくブックマークしたときに検索が速くなる気がするのですがどうですか？

**Comment by oshibori** [comment]
ranking 昇順はいらないのでは？

**Comment by NotFounds** [comment]
defaultで昇順でいいですかね

**Comment by kinironote** [comment]
> threadにurlをhashしたものをindexとして保持させておくことで，他のユーザーが新しくブックマークしたときに検索が速くなる気がするのですがどうですか？

適切な設定をすればPostgresがやってくれそう
https://www.postgresql.jp/document/9.2/html/indexes-types.html

**Comment by NotFounds** [comment]
Entry

**Comment by kinironote** [comment]
url投げたら対応するentryのidを返してくれるものが欲しいです（ChromeExtensionでurlに対するコメント一覧が見たい）

**Comment by NotFounds** [comment]
一旦このissue閉じて，新しく開きます．
#32
