### ISSUE TITLE
Ranking API の設計について

### ISSUE THREAD

**Issue by tomoyaf** [enpitut2018/VideoSocialBookmark#4]
/rankingをたたいて帰ってくるJSONは生のThreadデータであるべきか？それともThreadのIDを持っていて、そのIDを用いて/threads/:idをたたくべきか？
  
APIを分けるとその分オーバーヘッドがかかりそう。
ただ、APIを分けたほうがDRYに見える。

**Comment by kinironote** [comment]
何十回も/threads/:idを叩くのはオーバーヘッドとても大きいのでは（idのリストを返すような実装を見たことがないので良くわからないけど）

**Comment by NotFounds** [comment]
n+1問題?
graphql使いたい欲が出てきますね。
個人的にはGET /thread/rankingは、thread objectのリストを返したいです。
リクエストパラメータでidのリストのみを返すオプションをつけるorフィールドを絞るのはありかなと思います。

**Comment by tomoyaf** [comment]
ではとりあえずthread objectのリストが返ってくるものとしてフロントエンドの実装します！
