### ISSUE TITLE
rating

### ISSUE THREAD

**Issue by NotFounds** [enpitut2018/VideoSocialBookmark#42]
今更だけど、Entryに対しては ⭐️ 5段階とかでも良さそうだなと思いました．

**Comment by kinironote** [comment]
ミシュラン五つ星みたいな方向性ならアリかもしれないけど
低評価〜高評価の５段階評価は微妙そう

個人的には評価をつけるのはユーザー的には楽しそうだから３段階くらいにして、かつ★1が低評価に思われないようしたい

コンテンツに評価をつけないほうがいいみたいな話あった気がするけど忘れてしまった
