### ISSUE TITLE
Entry Star

### ISSUE THREAD

**Issue by NotFounds** [enpitut2018/VideoSocialBookmark#6]
# Star
- [magnusvk/counter_culture](https://github.com/magnusvk/counter_culture)

### ⭐️ をつける
`POST /api/v1/stars`

#### Query
- thread_id
  + **int**
    + **required**
- user_id
  + **int**
    + **required**

#### Response
- Status: 200

### ⭐️ を消す
`DELETE /api/v1/stars/:id`
- id
  + thread_id

## Schema
|name|type|remarks|
|:-|:-|:-|
|id|BIGINT||
|thread_id|BIGINT||
|user_id|BIGINT||

thread_idとuser_idのペアは**unique**

**Comment by oshibori** [comment]
bookmarkとstarって何が違うんですか

**Comment by kinironote** [comment]
idが分からないので`POST /api/v1/stars`はidを返すか、`DELETE /api/v1/stars/:id`と同じQueryを貰わないとだめそう

**Comment by tomoyaf** [comment]
将来的には
- comment
- entry
- user
を評価したくなる可能性があると考えると対象を指定したいかも
`POST /api/v1/comments/:id/`
みたいな感じ

**Comment by NotFounds** [comment]
## Schema
|name|type|remarks|
|:-|:-|:-|
|id|BIGINT||
|target_id|BIGINT||
|target_kind|INTEGER|
|user_id|BIGINT||

**Comment by tomoyaf** [comment]
## API
`POST /api/v1/stars/entries/:entry_id`
`POST /api/v1/stars/comment/:comment_id`
`DELETE /api/v1/stars/entries/:entry_id`
`DELETE /api/v1/stars/comment/:entry_id`
