### ISSUE TITLE
ユーザーストーリー

### ISSUE THREAD

**Issue by NotFounds** [enpitut2018/VideoSocialBookmark#8]
ユーザーがサービスを使う一連の流れを確認する．

**Comment by NotFounds** [comment]
## 前提
ユーザーは、複数の動画サイトをまんべんなく視聴する。

# ストーリーA：話題の動画が見たい人
1. VSBにアクセスして、トップページでトレンドを見る
2. 気になった動画をプレイリストに追加
3. 動画を再生

# ストーリーB：動画をブックマークしておきたい人
1. 各サイトで動画を見る
2. 面白かったのでChrome Extensionからブックマークする
3. (コメントやレーティングを行う)
4. (ブックマークしたことをTwitter等でシェアする)
5. (プレイリストに追加する)

**Comment by tomoyaf** [comment]
# ストーリーC：作業用に動画を掛けておきたい人
(あらがじめ何らかの方法でプレイリストを作成する)
1. プレイリストを選ぶ
2. プレイリストをかけっぱなしにする

**Comment by tomoyaf** [comment]
> ## 前提
> ユーザーは、複数の動画サイトをまんべんなく視聴する。
> 
> # ストーリーA：話題の動画が見たい人
> 1. VSBにアクセスして、トップページでトレンドを見る
> 2. 気になった動画をプレイリストに追加
> 3. 動画を再生
> 
> # ストーリーB：動画をブックマークしておきたい人
> 1. 各サイトで動画を見る
> 2. 面白かったのでChrome Extensionからブックマークする
> 3. (コメントやレーティングを行う)
> 4. (ブックマークしたことをTwitter等でシェアする)
> 5. (プレイリストに追加する)

ストーリーAPIで話題の動画の中で気になった動画を見る際にプレイリストに追加するのは任意でもよいかも？

**Comment by kinironote** [comment]
フォロー（購読とかwatch？）機能があったらよさそう　タイムラインみたいな
程よい量のブックマークが溜まればTwitterみたいに新規分を全部チェックしそう

**Comment by kinironote** [comment]
機能を作れそうなところ
- 複数の動画サイトをまとめてないとできないこと
- Youtubeとニコ動がまとめてあってできること
- コメントによって作られるコミュニティが無いとできないこと（Twitterとかみたいな）
- 既存のサービスが作ってない新しい面白い機能（難しそう）
