### ISSUE TITLE
コメントしたときに自動でブックマークしないようにする

### ISSUE THREAD

**Issue by tomoyaf** [enpitut2018/VideoSocialBookmark#89]
**提案内容**

コメントしたら自動でブックマークされてるのは実際に使ってみて違和感を感じたのですがどうでしょう
モデル的にコメントはブックマークの可否に依存しないようにしたので簡単に修正できます
意見ほしいです

**タスク**
System
- [x] 自動でブックマークしている処理を消す

**その他**

**Comment by kinironote** [comment]
たしかに
